apiVersion: v1
kind: Service
metadata:
  name: netflix-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  loadBalancerClass: eks.amazonaws.com/nlb
  selector:
    app: netflix-app
  ports:
    - port: 80
      targetPort: 80
